### ISSUE TITLE
Is it okay if I embed this into my version of vMenu?

### ISSUE THREAD

**Issue by ghost** [Shrimpey/EnhancedCamera#2]
Hi. I'm currently making a forked version of vMenu, and I was wondering if I can embed this into my vMenu? It's easier as the Enhanced Cam would be visible within vMenu, instead of pressing a standalone button.

**Comment by Shrimpey** [comment]
Yes, absolutely, some servers already embed this in vMenu or other menus of their own. Feel free to do so as well.

**Comment by ghost** [comment]
Amazing, thank you! The branch is already available on my vMenu as I'm still trying to debug it, but hopefully I'll be able to get it working. :)
